### ISSUE TITLE
delete conversation

### ISSUE THREAD

**Issue by mohsenD98** [mohsenD98/QmlZeroDay#1]

**Comment by MidnightCoder-m** [comment]
## default: 
![image](https://user-images.githubusercontent.com/36326627/183254781-de3ceaf3-418d-4711-86b3-88100b046ddf.png)

## selected:
![image](https://user-images.githubusercontent.com/36326627/183254793-25bbb35b-82af-4f63-afc1-84c5f79cc212.png)
