### ISSUE TITLE
Edit new Coversation page( new contact )

### ISSUE THREAD

**Issue by mohsenD98** [mohsenD98/QmlZeroDay#22]

**Comment by MidnightCoder-m** [comment]
## current :    
![image](https://user-images.githubusercontent.com/36326627/182894524-b81f480b-cb08-4e1a-b3f9-f99bf97364b8.png)

**Comment by MidnightCoder-m** [comment]
# NEW:    
![image](https://user-images.githubusercontent.com/36326627/182933212-b912be10-e000-4498-a6c7-f283ee503b10.png)

![image](https://user-images.githubusercontent.com/36326627/182933262-4c7c0e6e-4dcc-40b4-ac2b-c8532a99bb58.png)
